/* ==========================================================================
   PIOST — interactions
   Language is URL-routed (/ = Korean, /en/ = English); each page is fully
   static. The English page is generated by scripts/build-en.mjs — edit the
   Korean index.html (content SoT) and the EN dictionary there, then rebuild.
   ========================================================================== */
(function () {
    'use strict';

    var REDUCED = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    var IS_EN = document.documentElement.lang === 'en';
    var COPIED_LABEL = IS_EN ? 'Copied!' : '복사됨!';

    /* ------------------------------------------------------------- nav */

    var nav = document.getElementById('nav');
    var scrollBar = document.getElementById('scrollBar');
    var ticking = false;

    function onScroll() {
        var y = window.scrollY;
        nav.classList.toggle('is-solid', y > 24);
        var max = document.documentElement.scrollHeight - window.innerHeight;
        scrollBar.style.transform = 'scaleX(' + (max > 0 ? Math.min(y / max, 1) : 0) + ')';
        ticking = false;
    }
    window.addEventListener('scroll', function () {
        if (!ticking) { requestAnimationFrame(onScroll); ticking = true; }
    }, { passive: true });
    onScroll();

    /* mobile menu */
    var menuBtn = document.getElementById('menuBtn');
    var navLinks = document.getElementById('navLinks');

    function closeMenu() {
        if (!navLinks.classList.contains('is-open')) return;
        var hadFocus = navLinks.contains(document.activeElement);
        navLinks.classList.remove('is-open');
        nav.classList.remove('is-menu-open');
        menuBtn.setAttribute('aria-expanded', 'false');
        if (hadFocus) menuBtn.focus();
    }
    menuBtn.addEventListener('click', function () {
        var open = !navLinks.classList.contains('is-open');
        navLinks.classList.toggle('is-open', open);
        nav.classList.toggle('is-menu-open', open);
        menuBtn.setAttribute('aria-expanded', String(open));
    });
    navLinks.addEventListener('click', function (e) {
        if (e.target.closest('a')) closeMenu();
    });
    document.addEventListener('keydown', function (e) {
        if (e.key === 'Escape') closeMenu();
    });

    /* scrollspy */
    var spyLinks = Array.prototype.slice.call(navLinks.querySelectorAll('a[href^="#"]'));
    var spyMap = {};
    spyLinks.forEach(function (a) { spyMap[a.getAttribute('href').slice(1)] = a; });

    var spyObserver = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
            var link = spyMap[entry.target.id];
            if (!link) return;
            if (entry.isIntersecting) {
                spyLinks.forEach(function (a) { a.classList.remove('is-active'); });
                link.classList.add('is-active');
            }
        });
    }, { rootMargin: '-40% 0px -55% 0px' });

    Object.keys(spyMap).forEach(function (id) {
        var section = document.getElementById(id);
        if (section) spyObserver.observe(section);
    });

    /* --------------------------------------------------------- reveal */

    document.querySelectorAll('.reveal-group').forEach(function (group) {
        Array.prototype.forEach.call(group.querySelectorAll(':scope > .reveal'), function (el, i) {
            el.style.setProperty('--reveal-delay', (Math.min(i, 7) * 70) + 'ms');
        });
    });

    var revealEls = document.querySelectorAll('.reveal');
    if (REDUCED) {
        revealEls.forEach(function (el) { el.classList.add('is-in'); });
    } else {
        var revealObserver = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    entry.target.classList.add('is-in');
                    revealObserver.unobserve(entry.target);
                }
            });
        }, { threshold: 0.1, rootMargin: '0px 0px -36px 0px' });
        revealEls.forEach(function (el) { revealObserver.observe(el); });
    }

    /* -------------------------------------------------------- counters */
    /* Preserves decimals ("11.7" stays 11.7) and comma grouping ("1,500"). */

    function animateCount(el) {
        var raw = el.textContent.trim();
        var target = parseFloat(raw.replace(/,/g, ''));
        if (isNaN(target)) return;
        var decimals = (raw.split('.')[1] || '').length;
        var grouped = raw.indexOf(',') !== -1;
        var start = null;
        var DURATION = 1300;

        function fmt(v) {
            return grouped
                ? v.toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })
                : v.toFixed(decimals);
        }
        function step(ts) {
            if (start === null) start = ts;
            var p = Math.min((ts - start) / DURATION, 1);
            var eased = 1 - Math.pow(1 - p, 4);
            el.textContent = p < 1 ? fmt(target * eased) : raw;
            if (p < 1) requestAnimationFrame(step);
        }
        requestAnimationFrame(step);
    }

    if (!REDUCED) {
        var countObserver = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    animateCount(entry.target);
                    countObserver.unobserve(entry.target);
                }
            });
        }, { threshold: 0.6 });
        document.querySelectorAll('[data-count]').forEach(function (el) { countObserver.observe(el); });
    }

    /* ---------------------------------------------------- email reveal */
    /* Click 1: reveal address. Click 2: copy + confirmation, then restore. */

    document.querySelectorAll('.email-reveal').forEach(function (btn) {
        btn.addEventListener('click', function () {
            var email = btn.dataset.email;
            if (!email) return;

            if (!btn.dataset.revealed) {
                btn.dataset.restore = btn.innerHTML;
                btn.dataset.revealed = '1';
                btn.textContent = email;
                return;
            }
            if (btn.dataset.copying) return;
            btn.dataset.copying = '1';

            var done = function () {
                btn.classList.add('is-copied');
                btn.textContent = '✓ ' + COPIED_LABEL;
                setTimeout(function () {
                    btn.classList.remove('is-copied');
                    btn.innerHTML = btn.dataset.restore;
                    delete btn.dataset.revealed;
                    delete btn.dataset.restore;
                    delete btn.dataset.copying;
                }, 1600);
            };

            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(email).then(done, done);
            } else {
                var ta = document.createElement('textarea');
                ta.value = email;
                ta.style.position = 'fixed';
                ta.style.opacity = '0';
                document.body.appendChild(ta);
                ta.select();
                try { document.execCommand('copy'); } catch (e) { /* best effort */ }
                document.body.removeChild(ta);
                done();
            }
        });
    });
})();
